version: "3.7"

services:
  web:
    build: 
      context: api
    ports:
      - "8000:80"
    environment: 
      ConnectionStrings__DB: Server=db;Database=master;User=sa;Password=PA$$W0RD
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU2-ubuntu-16.04"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "PA$$W0RD"
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"
