version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SA_PASSWORD: 1Secure*Password1
      MSSQL_PID: Express
      ACCEPT_EULA: Y

  migration:
    build:
      context: backend
      dockerfile: WebApi/EloBaza.MigrationTool/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: LocalDocker
      ConnectionStrings__AppConfig: ${ConnectionStrings__AppConfig}
    depends_on:
      - db

  api:
    build:
      context: backend
      dockerfile: WebApi/EloBaza.WebApi/Dockerfile
    ports:
      - "8001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: LocalDocker
      ConnectionStrings__AppConfig: ${ConnectionStrings__AppConfig}
    depends_on:
      - migration

  ui:
    build:
      context: ui
    ports:
      - "8000:80"
    depends_on:
      - api

volumes:
  mssql-data:
    driver: local
