version: "3.7"

services:
  ui:
    build:
      context: ui
    ports:
      - "8000:80"
    depends_on:
      - web

  web:
    build:
      context: api
      dockerfile: src/EloBaza.WebApi/Dockerfile
    ports:
      - "8001:80"
    environment:
      ConnectionStrings__DB: Server=db;Database=elo-baza;User=sa;Password=1Secure*Password1;MultipleActiveResultSets=true
    depends_on:
      - migration

  migration:
    build:
      context: api
      dockerfile: src/EloBaza.MigrationTool/Dockerfile
    environment:
      ConnectionStrings__DB: Server=db;Database=elo-baza;User=sa;Password=1Secure*Password1;MultipleActiveResultSets=true
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SA_PASSWORD: 1Secure*Password1
      MSSQL_PID: Express
      ACCEPT_EULA: Y

volumes:
  mssql-data:
