// <auto-generated />
using System;
using EloBaza.MigrationTool.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EloBaza.MigrationTool.Migrations
{
    [DbContext(typeof(EloBazaDbContext))]
    partial class EloBazaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EloBaza.Domain.Question.Answer", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AnswerId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<Guid>("Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("Question_id")
                        .HasColumnType("int");

                    b.HasKey("_id")
                        .HasName("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("Question_id");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("EloBaza.Domain.Question.Attachment", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AttachmentId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int?>("Explanation_id")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUri")
                        .IsRequired()
                        .HasColumnType("varchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("_id")
                        .HasName("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("Explanation_id");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasFilter("[QuestionId] IS NOT NULL");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("EloBaza.Domain.Question.Explanation", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ExplanationId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("_id")
                        .HasName("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasFilter("[QuestionId] IS NOT NULL");

                    b.ToTable("Explanation");
                });

            modelBuilder.Entity("EloBaza.Domain.Question.QuestionAggregate", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("QuestionId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<Guid>("Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("_categoryId")
                        .HasColumnType("int");

                    b.Property<int?>("_examSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("_subjectId")
                        .HasColumnType("int");

                    b.HasKey("_id")
                        .HasName("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("_categoryId");

                    b.HasIndex("_examSessionId");

                    b.HasIndex("_subjectId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("EloBaza.Domain.Subject.Category", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CategoryId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ParentCategory_id")
                        .HasColumnType("int");

                    b.Property<int?>("Subject_id")
                        .HasColumnType("int");

                    b.HasKey("_id")
                        .HasName("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("ParentCategory_id");

                    b.HasIndex("Subject_id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("EloBaza.Domain.Subject.ExamSession", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ExamSessionId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<byte?>("ResitNumber")
                        .HasColumnType("tinyint");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<int?>("Subject_id")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("_id")
                        .HasName("Id");

                    b.HasAlternateKey("Key");

                    b.HasIndex("Subject_id");

                    b.ToTable("ExamSession");
                });

            modelBuilder.Entity("EloBaza.Domain.Subject.SubjectAggregate", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SubjectId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("_id")
                        .HasName("Id");

                    b.HasAlternateKey("Key");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("EloBaza.Domain.Question.Answer", b =>
                {
                    b.HasOne("EloBaza.Domain.Question.QuestionAggregate", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("Question_id")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EloBaza.Domain.Question.Attachment", b =>
                {
                    b.HasOne("EloBaza.Domain.Question.Explanation", "Explanation")
                        .WithMany("Attachments")
                        .HasForeignKey("Explanation_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EloBaza.Domain.Question.QuestionAggregate", "Question")
                        .WithOne("Attachment")
                        .HasForeignKey("EloBaza.Domain.Question.Attachment", "QuestionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EloBaza.Domain.Question.Explanation", b =>
                {
                    b.HasOne("EloBaza.Domain.Question.QuestionAggregate", "Question")
                        .WithOne("Explanation")
                        .HasForeignKey("EloBaza.Domain.Question.Explanation", "QuestionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EloBaza.Domain.Question.QuestionAggregate", b =>
                {
                    b.HasOne("EloBaza.Domain.Subject.Category", null)
                        .WithMany()
                        .HasForeignKey("_categoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EloBaza.Domain.Subject.ExamSession", null)
                        .WithMany()
                        .HasForeignKey("_examSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EloBaza.Domain.Subject.SubjectAggregate", null)
                        .WithMany()
                        .HasForeignKey("_subjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EloBaza.Domain.Subject.Category", b =>
                {
                    b.HasOne("EloBaza.Domain.Subject.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategory_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EloBaza.Domain.Subject.SubjectAggregate", "Subject")
                        .WithMany("Categories")
                        .HasForeignKey("Subject_id")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EloBaza.Domain.Subject.ExamSession", b =>
                {
                    b.HasOne("EloBaza.Domain.Subject.SubjectAggregate", "Subject")
                        .WithMany("ExamSessions")
                        .HasForeignKey("Subject_id")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
